version: "3"

networks:
  hyhsystem:
    external: false

services:
  server:
    image: hyhsystem.cn
    container_name: hyhsystem.cn
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html:rw
    networks:
      - hyhsystem
    ports:
      - "65180:80"
