version: "3"

networks:
  docs:
    external: false

services:
  server:
    image: docs.hyhsystem.cn
    container_name: docs.hyhsystem.cn
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html:rw
    networks:
      - docs
    ports:
      - "65181:80"
